language: node_js
node_js: 
  - "stable"
env:
  global:
  - CODECLIMATE_REPO_TOKEN=2ab3b8d55f23c61b22e8ac6866badaf177bf6a87922f14bc4f11e0e3bbd00d97
before_script: 
  - cd Api
  - npm install
  - chmod 0755 node_modules/.bin/mocha
script:  
  - npm run test:travis
after_script:
  - npm run coverage
cache:
  directories:
    - "Api/node_modules"